"$schema" = 'https://starship.rs/config-schema.json'

format = "$all$line_break$shell$character"

[kubernetes]
disabled = true

[status]
disabled = false

[time]
disabled = true

[aws]
force_display = false

[shell]
disabled = false
bash_indicator = "bash"
fish_indicator = "fish"
unknown_indicator = "????"

[docker_context]
detect_files = [
    'docker-compose.yml',
    'docker-compose.yaml',
    'compose.yml',
    'compose.yaml',
    'Dockerfile'
]
