format = "$all$line_break$aws$line_break$shell$character"

[kubernetes]
disabled = false

[status]
disabled = false

[aws]
force_display = true

[shell]
disabled = false
bash_indicator = "bash"
fish_indicator = "fish"
unknown_indicator = "????"
