"$schema" = 'https://starship.rs/config-schema.json'

format = "$all$line_break$shell$character"

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'
disabled = true

[status]
disabled = false

[time]
format = '\[[$time]($style)\]'
disabled = true

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
force_display = false

[shell]
disabled = false
bash_indicator = "bash"
fish_indicator = "fish"
unknown_indicator = "????"

[docker_context]
format = '\[[$symbol$context]($style)\]'
detect_files = [
  'docker-compose.yml',
  'docker-compose.yaml',
  'compose.yml',
  'compose.yaml',
  'Dockerfile',
]
