format = "$all$line_break$aws$line_break$shell$character"

[kubernetes]
disabled = true

[status]
disabled = false

[aws]
force_display = true

[shell]
disabled = false
bash_indicator = "bash"
fish_indicator = "fish"
unknown_indicator = "????"

[docker_context]
detect_files = [
    'docker-compose.yml',
    'docker-compose.yaml',
    'compose.yml',
    'compose.yaml',
    'Dockerfile'
]
